# Generated by Django 3.2.6 on 2021-08-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('points', models.SmallIntegerField(verbose_name='points')),
                ('difficulty', models.IntegerField(choices=[(0, 'super mega easy '), (1, 'easy enough'), (2, 'medium'), (3, 'medium ++'), (4, 'harde'), (6, "don't try it")], default=0, verbose_name='difficulty')),
                ('is_active', models.BooleanField(default=True, verbose_name='is activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updates_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('is_active', models.BooleanField(default=True, verbose_name='is activ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updates_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.questions', verbose_name='Questions')),
            ],
        ),
    ]
